spring:
  application:
    name: trading-assistant
  # DB temporaire
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tradingdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
